<template>
  <div class="search-games">
      <b-container fluid class="bv-example-row">
       <b-row>
         <b-col>
                    
       <div class="card">
            <div class="card-content">

            <b-row>
                <b-col sm="8">
                    <label for="teste" class="mt-2">Game:</label>
                    <v-select id="teste" class="mt-2" style="width:50%" :options="games" v-model="selected"></v-select></b-col>
                <b-col sm="4">
                    <label for="teste1" class="mt-2">Filter by:</label>
                    <v-select id="teste1" class="mt-2"  style="width:60%"  :options="categories" v-model="selectedCategory"></v-select>
                </b-col>
            </b-row>               
  
                    
            <b-row cols="1" cols-sm="2" cols-md="3" cols-lg="4">
       
            <b-col
              v-for="(game, id) in filterGames"
              :key="id"
              col
              no-gutters
              class="mb-2 mt-3">
            
              <b-card 
                :title="game.name"
                :img-src="getPic(game.imageUrl)"
                :img-alt="game.imageUrl"
                img-height="170px"
                img-top
                style="max-width: 18rem; margin-top: 10px"> 
                
                <b-card-text>
                  {{ game.spots }} spots
                </b-card-text>
                
                <b-button variant="outline-primary" @click="toParty(game.id)">Visualizar</b-button>
                    </b-card>  
                    </b-col>
            
                </b-row>  
            </div>
       </div>

    </b-col>
   </b-row>
 </b-container>
  </div>
</template>

<script>

import axios from 'axios'
import {baseApiUrl, showError} from '../../../global'

export default {
    name: 'Games',
    data(){
        return{
            games:[],
            selected: null,
            selectedCategory: null,
            listGames: [],
            categories: []
        }
    },
    methods:{
         getPic(index) {
            return require('../../assets/games/'+index+'.jpg')
        },
        loadCombo(){
            axios.get(`${baseApiUrl}/games`)
            .then(res =>{
                this.games = res.data.map(item =>{
                    return {label: item.name, key: item.id}
                })
            }).catch(showError)
        },
        loadGames(){
            axios.get(`${baseApiUrl}/game/parties`)
            .then(res =>{
                res.data.map((item,index) =>{
                 
                    this.listGames.push(item)
                    if(item.spots === null){
                        this.listGames[index].spots = 0
                    }
                })
            }).catch(showError)
        },
        loadCategories(){
             axios.get(`${baseApiUrl}/game/categories`)
            .then(res =>{                
                this.categories = res.data.map(item =>{
                    return {label: item.name, key: item.id}
                })
            }).catch(showError)
        },toParty(gameId){
             this.$router.push({ name:'PartyGameId', params: {id: gameId}})
        }

    },
    created(){
        this.loadCombo()
        this.loadGames()
        this.loadCategories()
    },
    computed:{
        filterGames(){
            if(this.selected !== null){
                return this.listGames.filter((item) => {
                    return item.id === this.selected.key;
                });
            
            }else if(this.selectedCategory !== null){
                 return this.listGames.filter((item) => {
                    return item.category === this.selectedCategory.key;
                });
            
            }else{
                return this.listGames;
            }
        }
    },
    watch:{
        'selected': function(){
           return

        }
    }
}
</script>

<style>
/*! bulma.io v0.9.1 | MIT License | github.com/jgthms/bulma */
/*! Generated by Bulma Customizer v0.2.0 | https://github.com/webmasterish/bulma-customizer */
.card {
  background-color: white;
  border-radius: 0.25rem;
  box-shadow: 0 0.5em 1em -0.125em rgba(10, 10, 10, 0.1), 0 0px 0 1px rgba(10, 10, 10, 0.02);
  color: #4a4a4a;
  max-width: 100%;
  position: relative;
}

.card-content {
  background-color: transparent;
  padding: 1.5rem;
}

</style>